---
- name: prepare xenial for ansible
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: install python2
    raw: apt-get install -qq python2.7 python

- name: Install and configure all components
  hosts: all
  become: yes
  become_method: sudo
  roles: 
  - base
  - timezone
  - ntp
  - ros2
  
